import { ObjectId } from 'mongoose';

/**
 * Represents the Roadmap generated by AI for a specific user.
 */
export class Roadmap {
  constructor(
    public readonly _id: string,
    public userId: string | ObjectId,
    public title: string,
    public description: string,
    public targetRole: string,

    public content: {
      moduleTitle: string;
      topics: {
        name: string;
        resources: string[];
        isCompleted: boolean;
      }[];
    }[],

    public progress: number,
    public isCompleted: boolean,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
  ) {}
}
